manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: ed56d81db79cf3a6e5dc02697277c0fad880ad34
      import: app/west.yml
  self:
    path: config
