manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: fff185eaee87b0cfe768d8f2a6f556c7e27d8f11
      import: app/west.yml
  self:
    path: config
